#!/bin/sh


BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')


URGENT=10
LOW_VALUE=25
MIDDLE_VALUE=65
HIGH_VALUE=90

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
echo " ${BATTERY_POWER}%"

	elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
		if [[ "${BATTERY_POWER}" -le "${URGENT}" ]]; then
			echo "  ${BATTERY_POWER}%"

	elif [[ "${BATTERY_STATE}" -ge "${URGENT_VALUE}" ]]; then
		echo "${BATTERY_POWER}%"
		

	elif [[ "${BATTERY_POWER}" -ge "${LOW_VALUE}" ]]; then
		echo "  ${BATTERY_POWER}%"

	elif [[ "${BATTERY_POWER}" -ge "${MIDDLE_VALUE}" ]]; then
		echo "  ${BATTERY_POWER}%"
	
	elif [[ "${BATTERY_POWER}" -ge "$HIGH_VALUE}" ]]; then
		echo "  ${BATTERY_POWER}%"
		
	fi

else
	echo "${BATTERY_POWER}%"
	echo "${BATTERY_POWER}%"
	echo ""
fi

case $BLOCK_BUTTON in
	1) notify-send "$(acpi -b | awk '{print $5, $6, $7}')" ;;
	3) echo "Right Click" ;;
esac
